config/routes.rb
Rails.application.routes.draw do
  # get 'appts/index'
  # get 'appts/new'
  root 'docs#index'

  resources :users
  resources :docs do
    resources :appts, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appt.rb
class Appt < ApplicationRecord
  belongs_to :doc
  belongs_to :user

  validates :date, :time, presence: true
end

app/models/doc.rb
class Doc < ApplicationRecord
  has_many :appts, dependent: :destroy
  has_many :users, through: :appts

  validates :dr_name, :dr_num, presence: true
  validates :dr_num, uniqueness: true
  validates :dr_name, :dr_num, length: { minimum: 1 }

  def full_name
    "#{self.dr_name} (aka: Dr. #{self.dr_num})"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appts, dependent: :destroy
  has_many :docs, through: :appts

  validates :first_name, :last_name, :patient_num, presence: true
  validates :patient_num, uniqueness: true
  validates :first_name, :last_name, :patient_num, length: { minimum: 1 }

  def full_name
    "#{self.first_name} #{self.last_name} (aka: #{self.patient_num})"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appts_controller.rb
class ApptsController < ApplicationController
  before_action :set_doc

  def index
    @doctors = @doc.appts
  end

  def new
    @users = User.all - @doc.users
    @appt = @doc.appts.new
  end

  def create
    @appt = @doc.appts.new(appt_params)
    if @appt.save
      redirect_to doc_path(@doc)
    else
      render :new
    end
  end
  
  def destroy
    @appt = @doc.appts.find(params[:id])
    @appt.destroy
    # redirect_to doc_appts_path(@doc)
    redirect_to doc_path(@doc)
  end

      private
      def set_doc
        @doc = Doc.find(params[:doc_id])
      end

      def appt_params
        params.require(:appt).permit(:date, :time, :user_id)
      end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.all
  end

  def show
    @doc_appts = @doc.appts
  end

  def new
    @doc = Doc.new
  end

  def create
    @doc = Doc.create(doc_params) #.create or .new?
    if @doc.save
      #May need to fix later:
      redirect_to docs_path
    else
      render :new
    end
  end

  def destroy
    @doc.destroy
    redirect_to ##
  end

  def edit
  end

  def update
    if @doc.update(doc_params)
        redirect_to doc_path
    else
      render :edit
    end
  end

  private
  def set_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:dr_name, :dr_num)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user_appts = @user.appts
  end

  def new
    @user = User.new
  end

  def edit
  end

def create
  @user = User.create(user_params) #.create or .new?
  if @user.save
    #May need to fix later:
    redirect_to users_path
  else
    render :new
  end
end

def update
  if @user.update(user_params)
     redirect_to user_path
  else
    render :edit
  end
end

def destroy
  @user.destroy
  redirect_to users_path
end 

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :patient_num)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appts_helper.rb
module ApptsHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appts/index.html.erb
<h1><%= @doc.dr_num %>'s Appointments</h1>
<%= link_to 'Add Appointment', new_doc_appt_path(@doc) %>
<hr />
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= doctor.user.full_name %>
      <br />
      <%= link_to 'Edit', doc_appt_path(@doc, doctor), method: :delete %>
      <%= link_to 'Remove', doc_appt_path(@doc, doctor), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/appts/new.html.erb
<h1>Add Appointments</h1>
<%= form_with(model: [@doc, @appt], local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :user %>
    <%= f.select :user_id, @users.collect { |u| [u.full_name, u.id] } %>
  </div>
  
  <div class="field">
    <%= f.label :Date_and_Time %>
    <%= f.date_field :date, required: true, placeholder: "Date" %>
    <%= f.time_field :time, required: true, placeholder: "Time" %>
  </div>
  <%= f.submit nil, class: "ui blue button" %>
<% end %>

app/views/docs/edit.html.erb
<h1>Edit Doctor Info</h1>
<hr />
<%= form_with(model: @doc, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <h3><%= f.label :Name %></h3>
    <%= f.text_field :dr_name, required: true, placeholder: "Doctor's Last Name" %>
    <%= f.text_field :dr_num, required: true, placeholder: "Doctor's Alias" %>
  </div>
  <%= f.submit 'Update Doc Info', class: "ui grey button" %>
  <%= link_to "Delete Doc", @doc, method: :delete, class: "ui red button" %>
<% end %>

app/views/docs/index.html.erb
<h1>Doctors</h1>
<%= link_to 'Add Doctor', new_doc_path %>
<hr />
<h2><%= @docs.length <= 0 ? "No Doctors" : "" %></h2> 
<ul>
  <% @docs.each do |doc| %>
    <li>
      <%= link_to doc.full_name, doc %>
    </li>
  <% end %>
</ul>

app/views/docs/new.html.erb
<h1>New Doctor</h1>
<%= form_with(model: @doc, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :dr_name, required: true, placeholder: "Doctor's Last Name" %>
    <%= f.text_field :dr_num, required: true, placeholder: "Doctor's Alias" %>
  </div>
  <%= f.submit 'Add Doctor', class: "ui grey button" %>
<% end %>

app/views/docs/show.html.erb
<h1><%= @doc.full_name %></h1>
<%= link_to 'Edit Doctor Info', edit_doc_path(@doc)%>
<hr />
<h3><%= @doc_appts.length <= 0 ? "No Appointments" : "Appointments" %>
<%= link_to 'Add', new_doc_appt_path(@doc), class: "ui blue button inverted" %></h3>
<div>
<ul>
  <% @doc_appts.each do |appt| %>
    <li>
      <%= "#{appt.user.full_name}: #{appt.date}" %>
      <br/>
      <%= link_to 'Cancel', doc_appt_path(@doc, appt), method: :delete %>
      <%= "Reschedule" %>
      <br/>
      <br/>
      </li>
  <% end %>
</ul>
</div>

app/views/layouts/_navbar.html.erb
<nav>
      <%= link_to 'PATIENTS', users_path, class: "ui white button"%>
      <%= link_to 'DOCTORS', docs_path, class: "ui white button"%>
</nav>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doctor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Edit Patient Info</h1>
<hr />
<%= form_with(model: @user, local: true, class: "ui form") do |f| %>
    <div class="field">
      <h2><%= f.label :Name %></h2>
        <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
        <%= f.text_field :last_name, required: true, autofocus: true, placeholder: "Last Name" %>
      <h2><%= f.label :Alias %></h2>
        <%= f.text_field :patient_num, required: true, placeholder: "Type Unique Alias" %>
    </div>
  <%= f.submit 'Update Patient Info', class: "ui grey button" %>
  <%= link_to "Delete Patient", @user, method: :delete, class: "ui red button" %>
<% end %>

app/views/users/index.html.erb
<h1>Patients</h1>
<%= link_to 'Add Patient', new_user_path %>
<hr />
<h2><%= @users.length <= 0 ? "No Patients" : "" %></h2> 
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.full_name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New Patient</h1>
  <%= form_with(model: @user, local: true, class: "ui form") do |f| %>
    <div class="field">
      <h2><%= f.label :Name %></h2>
        <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
        <%= f.text_field :last_name, required: true, autofocus: true, placeholder: "Last Name" %>
      <h2><%= f.label :Alias %></h2>
        <%= f.text_field :patient_num, required: true, placeholder: "Type Unique Alias" %>
    </div>
  <%= f.submit 'Add Patient', class: "ui grey button" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %></h1>
<%= link_to 'Edit Patient Info', edit_user_path(@user)%>
<hr />
<h3><%= @user_appts.length <= 0 ? "No Appointments" : "Appointments" %>
<%= link_to 'Add', class: "ui blue button inverted" %></h3>
<ul>
  <% @user_appts.each do |appt| %>
    <li>
      <%= "#{appt.doc.dr_name} (#{appt.doc.dr_num}): #{appt.date}" %>
      <br/>
      <%= "Cancel"%>
      <%= "Reschedule" %>
      <br/>
      <br/>
    </li>
  <% end %>
</ul>